name: Build
on:
  push:
    branches:
    - main
jobs:
  version:
    name: Assign Version
    runs-on: mtaylorio-runners-k8s
    container:
      image: images.home.mtaylor.io/deployer:0.0.9
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: version
      name: Generate Version Tag
      run: |
        set -eux
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git fetch origin 'refs/tags/*:refs/tags/*'
        export tag=$(get-release-tag)
        echo "tag=$tag" >> $GITHUB_OUTPUT
  tag:
    name: Tag Repository
    runs-on: mtaylorio-runners-k8s
    container:
      image: images.home.mtaylor.io/deployer:0.0.9
    needs: [version]
    outputs:
      sha: ${{ steps.tag.outputs.sha }}
      tag: ${{ needs.version.outputs.tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: tag
      name: Tag
      shell: bash
      run: |
        set -euxo pipefail
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git config --global user.email "githubactions@mtaylor.io"
        git config --global user.name "GitHub Actions"
        git tag -a ${{ needs.version.outputs.tag }} -m "Release ${{ needs.version.outputs.tag }}"
        git push origin ${{ needs.version.outputs.tag }}
        sha=$(git rev-parse --short HEAD)
        echo "sha=$sha" >> $GITHUB_OUTPUT
  docker:
    name: Docker Build
    runs-on: mtaylorio-runners-dind
    needs: [tag]
    outputs:
      sha: ${{ needs.tag.outputs.sha }}
      tag: ${{ needs.tag.outputs.tag }}
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Checkout
      uses: actions/checkout@v4
    - id: meta
      name: Docker Metadata
      uses: docker/metadata-action@v5
      with:
        images: images.home.mtaylor.io/elm
        tags: |
          latest
          ${{ needs.tag.outputs.tag }}
          sha-${{ needs.tag.outputs.sha }}
    - name: Docker Build
      uses: docker/build-push-action@v6
      with:
        push: true
        context: "."
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
